### ISSUE TITLE
Crash on when touch the screen

### ISSUE THREAD

**Issue by pankajjangid** [BeyondAR/beyondar#105]
08-08 10:47:53.064 1070-1566/googlemapar.pankaj.com.googlemapar E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: googlemapar.pankaj.com.googlemapar, PID: 1070
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.beyondar.android.world.World.getBeyondarObjectsCollideRay(com.beyondar.android.util.math.geom.Ray, java.util.ArrayList, float)' on a null object reference
        at googlemapar.pankaj.com.googlemapar.ui.ArBeyondarGLSurfaceView.getBeyondarObjectsOnScreenCoordinates(ArBeyondarGLSurfaceView.java:261)
        at googlemapar.pankaj.com.googlemapar.ui.ArBeyondarGLSurfaceView.getBeyondarObjectsOnScreenCoordinates(ArBeyondarGLSurfaceView.java:241)
        at googlemapar.pankaj.com.googlemapar.ui.ArFragmentSupport$1.run(ArFragmentSupport.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

08-08 10:47:53.068 1070-1566/googlemapar.pankaj.com.googlemapar W/OPDiagnose: getService:OPDiagnoseService NULL

**Comment by luciadcf** [comment]
That is cause you are not setting the world parameter to the BeyondarFragmentSupport.
