### ISSUE TITLE
Examples crash while running

### ISSUE THREAD

**Issue by kum-rah** [BeyondAR/beyondar#74]
Hi,
I am new to android, and tried to run the examples given here, https://github.com/BeyondAR/beyondar/tree/master/android/BeyondAR_Examples

Unfortunately except the GoogleMapActivity, all other activities crash when i try to run them. there was a similar question on your previous forum. http://beyondar.com/node/84

Below is the information displayed on the logcat when i run the example on Android4.4.4 device(API 19).

06-23 15:03:01.306  22384-22384/com.example.nmsl.bdemo2 V/BeyondAR_camera﹕ getTheCamera
06-23 15:03:01.436  22384-22384/com.example.nmsl.bdemo2 V/BeyondAR_camera﹕ acquired the camera
06-23 15:03:01.456  22384-22384/com.example.nmsl.bdemo2 W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x4176fe30)
06-23 15:03:01.466  22384-22384/com.example.nmsl.bdemo2 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.nmsl.bdemo2, PID: 22384
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.nmsl.bdemo2/com.example.nmsl.CameraWithScreenShotActivity}: java.lang.IllegalStateException: com.beyondar.android.fragment.BeyondarFragmentSupport can not run without the compass sensor.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2439)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
            at android.app.ActivityThread.access$800(ActivityThread.java:153)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5633)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: com.beyondar.android.fragment.BeyondarFragmentSupport can not run without the compass sensor.
            at com.beyondar.android.fragment.BeyondarFragmentSupport.checkIfSensorsAvailable(BeyondarFragmentSupport.java:108)
            at com.beyondar.android.fragment.BeyondarFragmentSupport.setWorld(BeyondarFragmentSupport.java:274)
            at com.example.nmsl.CameraWithScreenShotActivity.onCreate(CameraWithScreenShotActivity.java:38)
            at android.app.Activity.performCreate(Activity.java:5312)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
            at android.app.ActivityThread.access$800(ActivityThread.java:153)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5633)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by igor-couto** [comment]
Your log says: 
"java.lang.IllegalStateException: com.beyondar.android.fragment.BeyondarFragmentSupport can not run without the compass sensor."

Did you put the permissions on your manifest? BeyondAR needs the following features:

```
<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.sensor.accelerometer" />
<uses-feature android:name="android.hardware.sensor.compass" />
```

**Comment by radhadamoder** [comment]
yes i have also same error and i also put these permissions in manifest.

**Comment by songrui233** [comment]
I got the same error in my project too.==

**Comment by radhadamoder** [comment]
actually this project is work on compass senser its compulsory the presence of compass senser on your device in which you are trying to run the app.
