### ISSUE TITLE
project crashes with mBeyondarFragment.setWorld

### ISSUE THREAD

**Issue by songrui233** [BeyondAR/beyondar#94]
Anyone has an idea with this log?Is it because the api15 is not supported or something wrong in my device?The error occured when I try to use mathod setWorld.

10-11 09:03:07.891: D/ActivityThread(8049): setTargetHeapUtilization:0.25
10-11 09:03:07.891: D/ActivityThread(8049): setTargetHeapIdealFree:8388608
10-11 09:03:07.891: D/ActivityThread(8049): setTargetHeapConcurrentStart:2097152
10-11 09:03:08.161: V/BeyondAR_camera(8049): getTheCamera
10-11 09:03:09.401: V/BeyondAR_camera(8049): acquired the camera
10-11 09:03:09.621: W/dalvikvm(8049): threadid=1: thread exiting with uncaught exception (group=0x40a8a390)
10-11 09:03:09.681: E/AndroidRuntime(8049): FATAL EXCEPTION: main
10-11 09:03:09.681: E/AndroidRuntime(8049): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.te.test/com.te.test.MainActivity}: java.lang.IllegalStateException: com.beyondar.android.fragment.BeyondarFragmentSupport can not run without the compass sensor.
10-11 09:03:09.681: E/AndroidRuntime(8049):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1959)
10-11 09:03:09.681: E/AndroidRuntime(8049):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1984)
10-11 09:03:09.681: E/AndroidRuntime(8049):     at android.app.ActivityThread.access$600(ActivityThread.java:126)
10-11 09:03:09.681: E/AndroidRuntime(8049):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1150)
10-11 09:03:09.681: E/AndroidRuntime(8049):     at android.os.Handler.dispatchMessage(Handler.java:99)
10-11 09:03:09.681: E/AndroidRuntime(8049):     at android.os.Looper.loop(Looper.java:137)
10-11 09:03:09.681: E/AndroidRuntime(8049):     at android.app.ActivityThread.main(ActivityThread.java:4456)
10-11 09:03:09.681: E/AndroidRuntime(8049):     at java.lang.reflect.Method.invokeNative(Native Method)
10-11 09:03:09.681: E/AndroidRuntime(8049):     at java.lang.reflect.Method.invoke(Method.java:511)
10-11 09:03:09.681: E/AndroidRuntime(8049):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
10-11 09:03:09.681: E/AndroidRuntime(8049):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
10-11 09:03:09.681: E/AndroidRuntime(8049):     at dalvik.system.NativeStart.main(Native Method)
10-11 09:03:09.681: E/AndroidRuntime(8049): Caused by: java.lang.IllegalStateException: com.beyondar.android.fragment.BeyondarFragmentSupport can not run without the compass sensor.
10-11 09:03:09.681: E/AndroidRuntime(8049):     at com.beyondar.android.fragment.BeyondarFragmentSupport.checkIfSensorsAvailable(BeyondarFragmentSupport.java:108)
10-11 09:03:09.681: E/AndroidRuntime(8049):     at com.beyondar.android.fragment.BeyondarFragmentSupport.setWorld(BeyondarFragmentSupport.java:274)
10-11 09:03:09.681: E/AndroidRuntime(8049):     at com.te.test.MainActivity.onCreate(MainActivity.java:30)
10-11 09:03:09.681: E/AndroidRuntime(8049):     at android.app.Activity.performCreate(Activity.java:4465)
10-11 09:03:09.681: E/AndroidRuntime(8049):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
10-11 09:03:09.681: E/AndroidRuntime(8049):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1923)
10-11 09:03:09.681: E/AndroidRuntime(8049):     ... 11 more

**Comment by idafroseth** [comment]
It seems like it cannot access your compass. Are you running on a real device or an emulator
Do you have the required permission in your manifest file?
`<uses-feature android:name="android.hardware.sensor.compass" />`

**Comment by songrui233** [comment]
@idafroseth 
Thanks a lot.But I do run the project on a real device and I had the permission too.

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.ggjj.arbeyond"
    android:versionCode="1"
    android:versionName="1.0" >
    <uses-sdk
        android:minSdkVersion="18"
        android:targetSdkVersion="18" />



<uses-permission android:name="android.permission.CAMERA" />



<uses-permission android:name="android.permission.INTERNET" />



<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.sensor.accelerometer" />
<uses-feature android:name="android.hardware.sensor.compass" />
    <application
        android:allowBackup="true"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>

**Comment by songrui233** [comment]
@idafroseth 

<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.sensor.accelerometer" />
<uses-feature android:name="android.hardware.sensor.compass" />

**Comment by songrui233** [comment]
``
<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.sensor.accelerometer" />
<uses-feature android:name="android.hardware.sensor.compass" />
